#pragma once

/* -----------------------------------------------------------------------
 * Dashboard page  (GET /)
 * ----------------------------------------------------------------------- */
#pragma once

/* -----------------------------------------------------------------------
 * Dashboard page — split at IP placeholder (GET /)
 * Usage: send PRE, then ip string, then POST
 * ----------------------------------------------------------------------- */
static const char HTML_DASHBOARD_PRE[] =
"<!DOCTYPE html><html lang='pt-br'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Epson Control</title>"
"<style>"
"*{box-sizing:border-box;font-family:sans-serif}"
"body{margin:0;background:#1a1a2e;color:#eee;display:flex;flex-direction:column;align-items:center;padding:20px}"
"h1{color:#e94560;margin-bottom:4px}small{color:#aaa;margin-bottom:20px;display:block;text-align:center}"
".card{background:#16213e;border-radius:12px;padding:16px;margin:8px;width:100%;max-width:480px}"
".card h3{margin-top:0;color:#e94560;font-size:14px;text-transform:uppercase;letter-spacing:1px}"
".btn-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}"
".btn-grid.cols3{grid-template-columns:repeat(3,1fr)}"
"button{padding:12px 8px;border:none;border-radius:8px;cursor:pointer;font-size:14px;font-weight:bold;transition:.2s}"
".btn-green{background:#27ae60;color:#fff}.btn-green:hover{background:#2ecc71}"
".btn-red{background:#c0392b;color:#fff}.btn-red:hover{background:#e74c3c}"
".btn-blue{background:#2980b9;color:#fff}.btn-blue:hover{background:#3498db}"
".btn-gray{background:#555;color:#fff}.btn-gray:hover{background:#777}"
".btn-full{grid-column:1/-1}"
"#status-box{background:#0d1117;border-radius:8px;padding:12px;font-size:13px;word-break:break-all;min-height:40px}"
"#toast{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#27ae60;color:#fff;padding:10px 20px;border-radius:8px;display:none;font-size:14px}"
"nav{display:flex;gap:10px;margin-bottom:16px}"
"nav a{color:#e94560;text-decoration:none;font-size:14px;padding:6px 12px;border:1px solid #e94560;border-radius:6px}"
"nav a:hover{background:#e94560;color:#fff}"
"</style></head><body>"
"<h1>&#127909; Epson Control</h1>"
"<small id='ip-label'>IP: ";

static const char HTML_DASHBOARD_POST[] =
"</small>"
"<nav>"
"<a href='/'>Dashboard</a>"
"<a href='/config'>&#9881; Config</a>"
"<a href='/ota'>&#8593; OTA</a>"
"</nav>"
"<div class='card'>"
"<h3>&#128161; Energia</h3>"
"<div class='btn-grid'>"
"<button class='btn-green' onclick='cmd(\"PWR ON\")'>&#9654; Ligar</button>"
"<button class='btn-red'   onclick='cmd(\"PWR OFF\")'>&#9646;&#9646; Desligar</button>"
"</div></div>"
"<div class='card'>"
"<h3>&#128250; Fonte de entrada</h3>"
"<div class='btn-grid cols3'>"
"<button class='btn-blue' onclick='cmd(\"SOURCE HDMI1\")'>HDMI 1</button>"
"<button class='btn-blue' onclick='cmd(\"SOURCE HDMI2\")'>HDMI 2</button>"
"<button class='btn-blue' onclick='cmd(\"SOURCE VGA\")'>VGA</button>"
"<button class='btn-blue btn-full' onclick='cmd(\"SOURCE COMP\")'>Componente</button>"
"</div></div>"
"<div class='card'>"
"<h3>&#128266; Audio / Imagem</h3>"
"<div class='btn-grid cols3'>"
"<button class='btn-gray' onclick='cmd(\"VOL+\")'>&#128264; Vol +</button>"
"<button class='btn-gray' onclick='cmd(\"VOL-\")'>&#128263; Vol -</button>"
"<button class='btn-gray' onclick='cmd(\"MUTE ON\")'>Mudo ON</button>"
"<button class='btn-gray' onclick='cmd(\"MUTE OFF\")'>Mudo OFF</button>"
"<button class='btn-gray' onclick='cmd(\"BLANK ON\")'>Blank ON</button>"
"<button class='btn-gray' onclick='cmd(\"BLANK OFF\")'>Blank OFF</button>"
"</div></div>"
"<div class='card'>"
"<h3>&#128202; Status do Projetor</h3>"
"<button class='btn-blue' style='width:100%;margin-bottom:8px' onclick='queryStatus()'>&#8635; Atualizar Status</button>"
"<div id='status-box'>Clique em Atualizar Status...</div>"
"</div>"
"<div id='toast'></div>"
"<script>"
"async function cmd(c){"
"  const r=await fetch('/cmd',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cmd:c})});"
"  const d=await r.json();"
"  toast(d.status==='ok'?'OK: '+c:'Erro: '+(d.message||'?'), d.status==='ok');"
"}"
"async function queryStatus(){"
"  const r=await fetch('/status');"
"  const d=await r.json();"
"  document.getElementById('status-box').innerHTML="
"    '<b>Energia:</b> '+d.pwr+'<br><b>Fonte:</b> '+d.source+'<br><b>Lampada:</b> '+d.lamp;"
"}"
"function toast(msg,ok){"
"  const t=document.getElementById('toast');"
"  t.textContent=msg;"
"  t.style.background=ok?'#27ae60':'#c0392b';"
"  t.style.display='block';"
"  setTimeout(()=>t.style.display='none',2500);"
"}"
"</script></body></html>";

/* -----------------------------------------------------------------------
 * Config page — split into 5 parts for value substitution (GET /config)
 * Order: PRE, ssid, MID1, tx_pin, MID2, rx_pin, MID3, udp_port, POST
 * ----------------------------------------------------------------------- */
static const char HTML_CONFIG_PRE[] =
"<!DOCTYPE html><html lang='pt-br'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Configurar - Epson Control</title>"
"<style>"
"*{box-sizing:border-box;font-family:sans-serif}"
"body{margin:0;background:#1a1a2e;color:#eee;display:flex;flex-direction:column;align-items:center;padding:20px}"
"h1{color:#e94560}"
".card{background:#16213e;border-radius:12px;padding:20px;width:100%;max-width:480px}"
"label{display:block;margin:12px 0 4px;font-size:14px;color:#aaa}"
"input{width:100%;padding:10px;border:1px solid #333;border-radius:6px;background:#0d1117;color:#eee;font-size:14px}"
"button{margin-top:16px;width:100%;padding:12px;background:#e94560;color:#fff;border:none;border-radius:8px;font-size:16px;cursor:pointer}"
"button:hover{background:#c0392b}"
"#msg{margin-top:12px;text-align:center;color:#27ae60;display:none}"
"nav{display:flex;gap:10px;margin-bottom:16px}"
"nav a{color:#e94560;text-decoration:none;font-size:14px;padding:6px 12px;border:1px solid #e94560;border-radius:6px}"
"nav a:hover{background:#e94560;color:#fff}"
"</style></head><body>"
"<h1>&#9881; Configurar</h1>"
"<nav><a href='/'>&#8592; Dashboard</a></nav>"
"<div class='card'>"
"<h3>WiFi</h3>"
"<label>SSID</label><input id='ssid' value='";

static const char HTML_CONFIG_MID1[] =
"'>"
"<label>Senha</label><input id='pass' type='password' placeholder='deixe em branco para manter'>"
"<h3>UART RS232 (MAX3232)</h3>"
"<label>GPIO TX (ESP32 para MAX3232 T1IN)</label><input id='tx' type='number' value='";

static const char HTML_CONFIG_MID2[] =
"' min='-1' max='48'>"
"<label>GPIO RX (MAX3232 R1OUT para ESP32)</label><input id='rx' type='number' value='";

static const char HTML_CONFIG_MID3[] =
"' min='-1' max='48'>"
"<h3>Servidor UDP</h3>"
"<label>Porta UDP</label><input id='udp' type='number' value='";

static const char HTML_CONFIG_POST[] =
"' min='1' max='65535'>"
"<button onclick='save()'>&#128190; Salvar e Reiniciar</button>"
"<div id='msg'>Salvo! Reiniciando...</div>"
"</div>"
"<script>"
"async function save(){"
"  const b={ssid:document.getElementById('ssid').value,"
"    pass:document.getElementById('pass').value,"
"    tx:parseInt(document.getElementById('tx').value),"
"    rx:parseInt(document.getElementById('rx').value),"
"    udp:parseInt(document.getElementById('udp').value)};"
"  const r=await fetch('/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});"
"  if(r.ok){document.getElementById('msg').style.display='block';}"
"}"
"</script></body></html>";

/* -----------------------------------------------------------------------
 * OTA page  (GET /ota)
 * ----------------------------------------------------------------------- */
static const char HTML_OTA[] =
"<!DOCTYPE html><html lang='pt-br'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>OTA Update - Epson Control</title>"
"<style>"
"*{box-sizing:border-box;font-family:sans-serif}"
"body{background:#1a1a2e;color:#eee;display:flex;flex-direction:column;align-items:center;padding:20px}"
"h1{color:#e94560}"
".card{background:#16213e;border-radius:12px;padding:20px;width:100%;max-width:480px}"
"input[type=file]{width:100%;padding:10px;border:1px dashed #555;border-radius:6px;background:#0d1117;color:#eee;margin:12px 0}"
"button{width:100%;padding:12px;background:#27ae60;color:#fff;border:none;border-radius:8px;font-size:16px;cursor:pointer}"
"button:hover{background:#2ecc71}"
"button:disabled{background:#555;cursor:not-allowed}"
"progress{width:100%;height:20px;margin-top:12px;border-radius:4px}"
"#log{margin-top:12px;background:#0d1117;padding:10px;border-radius:6px;font-size:12px;min-height:60px;color:#0f0}"
"nav a{color:#e94560;text-decoration:none;font-size:14px;padding:6px 12px;border:1px solid #e94560;border-radius:6px}"
"nav a:hover{background:#e94560;color:#fff}"
"nav{margin-bottom:16px}"
"</style></head><body>"
"<h1>&#8593; OTA Firmware Update</h1>"
"<nav><a href='/'>&#8592; Dashboard</a></nav>"
"<div class='card'>"
"<p style='color:#aaa;font-size:14px'>Selecione o arquivo <b>.bin</b> gerado pelo ESP-IDF: build/epson-control.bin</p>"
"<input type='file' id='fw' accept='.bin'>"
"<button id='btn' onclick='upload()'>&#8679; Enviar Firmware</button>"
"<progress id='prog' value='0' max='100' style='display:none'></progress>"
"<div id='log'>Aguardando arquivo...</div>"
"</div>"
"<script>"
"async function upload(){"
"  const f=document.getElementById('fw').files[0];"
"  if(!f){document.getElementById('log').textContent='Selecione um arquivo .bin';return;}"
"  document.getElementById('btn').disabled=true;"
"  const prog=document.getElementById('prog');"
"  const log=document.getElementById('log');"
"  prog.style.display='block';prog.value=0;"
"  log.textContent='Enviando '+f.name+' ('+Math.round(f.size/1024)+' KB)...';"
"  const xhr=new XMLHttpRequest();"
"  xhr.open('POST','/ota');"
"  xhr.upload.onprogress=e=>{if(e.lengthComputable)prog.value=Math.round(e.loaded/e.total*100);};"
"  xhr.onload=()=>{"
"    if(xhr.status===200){log.textContent='Upload concluido! Reiniciando...';}"
"    else{log.textContent='Erro: '+xhr.responseText;document.getElementById('btn').disabled=false;}"
"  };"
"  xhr.onerror=()=>{log.textContent='Erro de conexao.';document.getElementById('btn').disabled=false;};"
"  xhr.send(f);"
"}"
"</script></body></html>";

/* -----------------------------------------------------------------------
 * Setup page shown in AP mode  (GET /)
 * ----------------------------------------------------------------------- */
static const char HTML_SETUP[] =
"<!DOCTYPE html><html lang='pt-br'><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Setup - Epson Control</title>"
"<style>"
"*{box-sizing:border-box;font-family:sans-serif}"
"body{background:#1a1a2e;color:#eee;display:flex;flex-direction:column;align-items:center;padding:30px}"
"h1{color:#e94560}"
".card{background:#16213e;border-radius:12px;padding:24px;width:100%;max-width:420px}"
"label{display:block;margin:10px 0 4px;font-size:14px;color:#aaa}"
"input{width:100%;padding:10px;border:1px solid #333;border-radius:6px;background:#0d1117;color:#eee;font-size:14px}"
"button{margin-top:16px;width:100%;padding:12px;background:#e94560;color:#fff;border:none;border-radius:8px;font-size:16px;cursor:pointer}"
"#msg{margin-top:12px;text-align:center;font-size:14px}"
"</style></head><body>"
"<h1>&#9881; Configuracao Inicial</h1>"
"<div class='card'>"
"<p style='color:#aaa;font-size:14px'>Configure WiFi e os pinos UART para o projetor Epson via RS232.</p>"
"<h3>WiFi</h3>"
"<label>SSID da rede</label><input id='ssid' placeholder='Nome da rede WiFi'>"
"<label>Senha</label><input id='pass' type='password' placeholder='Senha WiFi'>"
"<h3>UART RS232 (MAX3232)</h3>"
"<label>GPIO TX (ESP32 para MAX3232 T1IN)</label><input id='tx' type='number' min='-1' max='48' value='5'>"
"<label>GPIO RX (MAX3232 R1OUT para ESP32)</label><input id='rx' type='number' min='-1' max='48' value='6'>"
"<h3>UDP</h3>"
"<label>Porta UDP (padrao: 4210)</label><input id='udp' type='number' value='4210' min='1' max='65535'>"
"<button onclick='save()'>&#128190; Salvar e Conectar</button>"
"<div id='msg'></div>"
"</div>"
"<script>"
"async function save(){"
"  const b={ssid:document.getElementById('ssid').value,"
"    pass:document.getElementById('pass').value,"
"    tx:parseInt(document.getElementById('tx').value),"
"    rx:parseInt(document.getElementById('rx').value),"
"    udp:parseInt(document.getElementById('udp').value)};"
"  if(!b.ssid){document.getElementById('msg').textContent='Informe o SSID!';return;}"
"  document.getElementById('msg').textContent='Salvando...';"
"  const r=await fetch('/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});"
"  if(r.ok)document.getElementById('msg').textContent='Salvo! O dispositivo vai reiniciar e conectar ao WiFi.';"
"  else document.getElementById('msg').textContent='Erro ao salvar.';"
"}"
"</script></body></html>";

